# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_timestamp', models.BigIntegerField()),
                ('to_timestamp', models.BigIntegerField()),
                ('comment', models.TextField()),
                ('patient', models.BigIntegerField()),
            ],
        ),
    ]
