# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-created_timestamp']},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='from_timestamp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='to_timestamp',
            field=models.BigIntegerField(null=True),
        ),
    ]
